version: '{build}'
branches:
  only:
  - master
skip_tags: true
image: Visual Studio 2022
configuration: Release
platform: Any CPU
build_script:
- ps: >-
    if ($env:APPVEYOR_PULL_REQUEST_NUMBER -eq $null -and $env:APPVEYOR_REPO_BRANCH -eq "master") {
      .\build.ps1 -Target DEFAULT
    } else {
      .\build.ps1 -Target AppVeyor
    }
test: off
deploy: off